# Generated by Django 4.2.11 on 2026-02-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="mobile_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Numéro mobile"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="mobile_operator",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mpesa", "M-Pesa"),
                    ("airtel", "Airtel Money"),
                    ("vodacom", "Vodacom M-Pesa"),
                    ("orange", "Orange Money"),
                ],
                max_length=20,
                null=True,
                verbose_name="Opérateur mobile",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="ID Transaction"
            ),
        ),
    ]
