# Generated by Django 4.2.11 on 2026-02-01 02:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom du partenaire"),
                ),
                (
                    "logo",
                    models.ImageField(upload_to="cms/partners/", verbose_name="Logo"),
                ),
                (
                    "logo_url",
                    models.URLField(blank=True, null=True, verbose_name="URL du logo"),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Site web"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Ordre")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
            ],
            options={
                "verbose_name": "Partenaire",
                "verbose_name_plural": "Partenaires",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        default="Mwolo Energy Systems",
                        max_length=200,
                        verbose_name="Nom de l'entreprise",
                    ),
                ),
                (
                    "company_description",
                    models.TextField(verbose_name="Description de l'entreprise"),
                ),
                (
                    "company_logo",
                    models.ImageField(upload_to="cms/logo/", verbose_name="Logo"),
                ),
                (
                    "company_logo_url",
                    models.URLField(blank=True, null=True, verbose_name="URL du logo"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=20, verbose_name="Téléphone")),
                ("address", models.TextField(verbose_name="Adresse")),
                (
                    "facebook_url",
                    models.URLField(blank=True, null=True, verbose_name="Facebook"),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, null=True, verbose_name="Twitter"),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, null=True, verbose_name="LinkedIn"),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, null=True, verbose_name="Instagram"),
                ),
                (
                    "google_maps_embed",
                    models.TextField(
                        blank=True,
                        help_text="Code d'intégration Google Maps",
                        verbose_name="Google Maps Embed",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
            ],
            options={
                "verbose_name": "Paramètres du site",
                "verbose_name_plural": "Paramètres du site",
            },
        ),
        migrations.RemoveField(
            model_name="service",
            name="icon",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="featured_video_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="URL vidéo (YouTube/Vimeo)"
            ),
        ),
        migrations.AddField(
            model_name="galleryimage",
            name="image_url",
            field=models.URLField(blank=True, null=True, verbose_name="URL image"),
        ),
        migrations.AddField(
            model_name="service",
            name="icon_svg",
            field=models.TextField(
                blank=True, help_text="Code SVG complet", verbose_name="Icône SVG"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="icon_url",
            field=models.URLField(blank=True, null=True, verbose_name="URL icône"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(verbose_name="Contenu"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="excerpt",
            field=models.CharField(blank=True, max_length=500, verbose_name="Résumé"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="featured_image",
            field=models.ImageField(
                upload_to="cms/blog_images/", verbose_name="Image principale"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Publié"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="meta_description",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Description SEO"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="meta_title",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Titre SEO"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de publication"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(max_length=300, verbose_name="Titre"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="title",
            field=models.CharField(max_length=300, verbose_name="Titre"),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="gallery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="cms.gallery",
                verbose_name="Galerie",
            ),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="image",
            field=models.ImageField(upload_to="cms/gallery/", verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Ordre"),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="title",
            field=models.CharField(blank=True, max_length=300, verbose_name="Titre"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="Prénom"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="is_contacted",
            field=models.BooleanField(default=False, verbose_name="Contacté"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="message",
            field=models.TextField(verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Téléphone"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="subject",
            field=models.CharField(max_length=300, verbose_name="Sujet"),
        ),
        migrations.AlterField(
            model_name="page",
            name="content",
            field=models.TextField(verbose_name="Contenu"),
        ),
        migrations.AlterField(
            model_name="page",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="page",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Publié"),
        ),
        migrations.AlterField(
            model_name="page",
            name="meta_description",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Description SEO"
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="meta_title",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Titre SEO"
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="og_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="cms/og_images/",
                verbose_name="Image OG",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="page",
            name="title",
            field=models.CharField(max_length=300, verbose_name="Titre"),
        ),
        migrations.AlterField(
            model_name="page",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
        ),
        migrations.AlterField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AlterField(
            model_name="service",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Ordre"),
        ),
        migrations.AlterField(
            model_name="service",
            name="title",
            field=models.CharField(max_length=300, verbose_name="Titre"),
        ),
        migrations.AlterField(
            model_name="service",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="author_image",
            field=models.ImageField(
                upload_to="cms/testimonials/", verbose_name="Photo"
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="author_name",
            field=models.CharField(max_length=200, verbose_name="Nom de l'auteur"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="author_title",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Titre/Poste"
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="content",
            field=models.TextField(verbose_name="Témoignage"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Ordre"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="rating",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                default=5,
                verbose_name="Note",
            ),
        ),
    ]
