# Generated by Django 4.2.11 on 2026-02-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0003_joboffer_sitesettings_hero"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="featured_image_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="URL image principale"
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="author_image_url",
            field=models.URLField(blank=True, null=True, verbose_name="URL photo"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="cms/blog_images/",
                verbose_name="Image principale",
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="cms/partners/", verbose_name="Logo"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="company_description",
            field=models.TextField(
                blank=True, verbose_name="Description de l'entreprise"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="company_logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="cms/logo/", verbose_name="Logo"
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="author_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="cms/testimonials/",
                verbose_name="Photo",
            ),
        ),
    ]
