# Generated by Django 4.2.11 on 2026-02-02 07:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0004_blogpost_featured_image_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advantage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "icon_name",
                    models.CharField(
                        blank=True,
                        help_text="Ex: zap, shield, smartphone, globe",
                        max_length=50,
                        verbose_name="Nom de l'icône",
                    ),
                ),
                (
                    "icon_svg",
                    models.TextField(
                        blank=True,
                        help_text="Code SVG complet de l'icône",
                        verbose_name="SVG personnalisé",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="cyan",
                        help_text="Ex: cyan, emerald, orange, purple",
                        max_length=50,
                        verbose_name="Couleur",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("order", models.IntegerField(default=0, verbose_name="Ordre")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
            ],
            options={
                "verbose_name": "Avantage",
                "verbose_name_plural": "Avantages (Pourquoi nous choisir)",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.CharField(max_length=500, verbose_name="Question")),
                ("answer", models.TextField(verbose_name="Réponse")),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Général, Facturation, Installation...",
                        max_length=100,
                        verbose_name="Catégorie",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("order", models.IntegerField(default=0, verbose_name="Ordre")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=200, verbose_name="Nom"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "subscribed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Inscrit le"),
                ),
                (
                    "unsubscribed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Désinscrit le"
                    ),
                ),
                (
                    "unsubscribe_token",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Token de désinscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonné newsletter",
                "verbose_name_plural": "Abonnés newsletter",
                "ordering": ["-subscribed_at"],
            },
        ),
        migrations.AddField(
            model_name="testimonial",
            name="client_code",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Code client"
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("approved", "Approuvé"),
                    ("rejected", "Rejeté"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=20, verbose_name="Téléphone")),
                ("cover_letter", models.TextField(verbose_name="Lettre de motivation")),
                (
                    "cv_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="cms/applications/",
                        verbose_name="CV (PDF)",
                    ),
                ),
                (
                    "cv_url",
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name="Lien vers CV (LinkedIn, Drive, etc.)",
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, null=True, verbose_name="LinkedIn"),
                ),
                (
                    "portfolio_url",
                    models.URLField(blank=True, null=True, verbose_name="Portfolio"),
                ),
                (
                    "expected_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Prétention salariale",
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Disponibilité"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("reviewed", "Examinée"),
                            ("interview", "Entretien"),
                            ("hired", "Embauché"),
                            ("rejected", "Rejetée"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes internes")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Candidature le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "job_offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="cms.joboffer",
                        verbose_name="Offre d'emploi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidature",
                "verbose_name_plural": "Candidatures",
                "ordering": ["-created_at"],
            },
        ),
    ]
