# Generated by Django 4.2.11 on 2026-02-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0005_advantage_faq_newslettersubscriber_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="post_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Post-nom"),
        ),
    ]
