# Generated by Django 4.2.11 on 2026-02-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0006_add_post_name_to_jobapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="portal_announcement",
            field=models.TextField(
                blank=True,
                help_text="Message affiché sur le portail employé",
                verbose_name="Annonce portail",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="portal_background_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="URL fond portail employé"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="portal_logo_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="URL logo portail"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="portal_primary_color",
            field=models.CharField(
                default="#0891b2",
                help_text="Code hex ex: #0891b2",
                max_length=7,
                verbose_name="Couleur primaire portail",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="portal_secondary_color",
            field=models.CharField(
                default="#2563eb",
                help_text="Code hex ex: #2563eb",
                max_length=7,
                verbose_name="Couleur secondaire portail",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="portal_welcome_message",
            field=models.CharField(
                default="Bienvenue sur votre espace de travail",
                max_length=200,
                verbose_name="Message d'accueil portail",
            ),
        ),
    ]
