# Generated by Django 4.2.11 on 2026-02-02 14:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0007_sitesettings_portal_announcement_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                (
                    "post_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Post-nom"
                    ),
                ),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "position",
                    models.CharField(max_length=200, verbose_name="Poste/Fonction"),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Département"
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biographie courte")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="cms/team/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "photo_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL de la photo"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, null=True, verbose_name="LinkedIn"),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, null=True, verbose_name="Twitter"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Affiché sur la page d'accueil",
                        verbose_name="En vedette",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
            ],
            options={
                "verbose_name": "Membre de l'équipe",
                "verbose_name_plural": "Membres de l'équipe",
                "ordering": ["order", "last_name"],
            },
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="company_slogan",
            field=models.CharField(
                default="L'énergie de demain, aujourd'hui",
                max_length=300,
                verbose_name="Slogan",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cta_button_text",
            field=models.CharField(
                default="Prendre rendez-vous",
                max_length=50,
                verbose_name="Texte bouton CTA",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cta_secondary_text",
            field=models.CharField(
                default="Trouver une agence",
                max_length=50,
                verbose_name="Texte bouton secondaire CTA",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cta_subtitle",
            field=models.TextField(
                default="Prenez rendez-vous avec nos experts pour une étude gratuite de votre projet.",
                verbose_name="Sous-titre CTA",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cta_title",
            field=models.CharField(
                default="Prêt pour une énergie fiable ?",
                max_length=300,
                verbose_name="Titre section CTA",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_cta_secondary_text",
            field=models.CharField(
                default="Nous contacter",
                max_length=50,
                verbose_name="Texte bouton secondaire",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_cta_text",
            field=models.CharField(
                default="Nos services",
                max_length=50,
                verbose_name="Texte bouton principal",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_highlight_word",
            field=models.CharField(
                default="énergétiques",
                help_text="Ce mot aura un dégradé de couleur",
                max_length=100,
                verbose_name="Mot à mettre en évidence",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_subtitle",
            field=models.TextField(
                default="Mwolo Energy Systems vous accompagne dans votre transition énergétique avec des solutions électriques et solaires innovantes et durables.",
                verbose_name="Sous-titre héro",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_title",
            field=models.CharField(
                default="Solutions énergétiques pour l'Afrique",
                max_length=300,
                verbose_name="Titre héro",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="login_background_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="URL fond page connexion client"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="register_background_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="URL fond page inscription"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="services_section_subtitle",
            field=models.TextField(
                default="Des solutions complètes pour répondre à tous vos besoins en électricité et énergie solaire",
                verbose_name="Sous-titre section services",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="services_section_title",
            field=models.CharField(
                default="Nos Services",
                max_length=200,
                verbose_name="Titre section services",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_team_section",
            field=models.BooleanField(
                default=True, verbose_name="Afficher section équipe"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_testimonials_section",
            field=models.BooleanField(
                default=True, verbose_name="Afficher section témoignages"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="team_section_subtitle",
            field=models.TextField(
                default="Des experts passionnés au service de votre transition énergétique",
                verbose_name="Sous-titre section équipe",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="team_section_title",
            field=models.CharField(
                default="Notre Équipe",
                max_length=200,
                verbose_name="Titre section équipe",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="testimonials_section_title",
            field=models.CharField(
                default="Ce que disent nos clients",
                max_length=200,
                verbose_name="Titre section témoignages",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="whatsapp_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Numéro WhatsApp"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="youtube_url",
            field=models.URLField(blank=True, null=True, verbose_name="YouTube"),
        ),
    ]
