# Generated by Django 4.2.11 on 2026-02-01 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("agencies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("post_name", models.CharField(blank=True, max_length=100)),
                ("nationality", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("place_of_birth", models.CharField(max_length=200)),
                ("nif", models.CharField(max_length=50, unique=True)),
                ("employee_number", models.CharField(max_length=20, unique=True)),
                ("position", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("cdd", "CDD"),
                            ("cdi", "CDI"),
                            ("consultant", "Consultant"),
                        ],
                        max_length=20,
                    ),
                ),
                ("hire_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("suspendu", "Suspendu"),
                            ("sorti", "Sorti"),
                        ],
                        default="actif",
                        max_length=20,
                    ),
                ),
                (
                    "base_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="agencies.agency",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employé",
                "verbose_name_plural": "Employés",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("days_per_year", models.IntegerField(default=20)),
            ],
            options={
                "verbose_name": "Type de congé",
                "verbose_name_plural": "Types de congés",
            },
        ),
        migrations.CreateModel(
            name="Leave",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("demande", "Demandé"),
                            ("approuve", "Approuvé"),
                            ("rejete", "Rejeté"),
                        ],
                        default="demande",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leaves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaves",
                        to="hr.employee",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="hr.leavetype"
                    ),
                ),
            ],
            options={
                "verbose_name": "Congé",
                "verbose_name_plural": "Congés",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Payroll",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("month", models.DateField()),
                ("base_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "bonuses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("net_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="payrolls/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payrolls",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bulletin de paie",
                "verbose_name_plural": "Bulletins de paie",
                "ordering": ["-month"],
                "unique_together": {("employee", "month")},
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("check_in", models.TimeField(blank=True, null=True)),
                ("check_out", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Présent"),
                            ("absent", "Absent"),
                            ("retard", "Retard"),
                            ("conge", "Congé"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Présence",
                "verbose_name_plural": "Présences",
                "ordering": ["-date"],
                "unique_together": {("employee", "date")},
            },
        ),
    ]
