# Generated by Django 4.2.11 on 2026-02-01 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("agencies", "0002_agency_province_alter_agency_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("geo", "0002_alter_commune_code_alter_commune_name_and_more"),
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="check_in",
            field=models.TimeField(blank=True, null=True, verbose_name="Arrivée"),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="check_out",
            field=models.TimeField(blank=True, null=True, verbose_name="Départ"),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="hr.employee",
                verbose_name="Employé",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Présent"),
                    ("absent", "Absent"),
                    ("retard", "Retard"),
                    ("conge", "Congé"),
                ],
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="agency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="agencies.agency",
                verbose_name="Agence",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="base_salary",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Salaire de base",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="contract_type",
            field=models.CharField(
                choices=[("cdd", "CDD"), ("cdi", "CDI"), ("consultant", "Consultant")],
                max_length=20,
                verbose_name="Type de contrat",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="date_of_birth",
            field=models.DateField(verbose_name="Date de naissance"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.CharField(max_length=100, verbose_name="Département"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emergency_contact_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Nom du contact d'urgence"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emergency_contact_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Téléphone du contact d'urgence"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_number",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Numéro d'employé"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="Prénom"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="hire_date",
            field=models.DateField(verbose_name="Date d'embauche"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="nationality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="geo.nationality",
                verbose_name="Nationalité",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="nif",
            field=models.CharField(max_length=50, unique=True, verbose_name="NIF"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="place_of_birth",
            field=models.CharField(max_length=200, verbose_name="Lieu de naissance"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(max_length=100, verbose_name="Poste"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="post_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Post-nom"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="status",
            field=models.CharField(
                choices=[
                    ("actif", "Actif"),
                    ("suspendu", "Suspendu"),
                    ("sorti", "Sorti"),
                ],
                default="actif",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_leaves",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approuvé par",
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="leave",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaves",
                to="hr.employee",
                verbose_name="Employé",
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="end_date",
            field=models.DateField(verbose_name="Date de fin"),
        ),
        migrations.AlterField(
            model_name="leave",
            name="leave_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="hr.leavetype",
                verbose_name="Type de congé",
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="reason",
            field=models.TextField(blank=True, verbose_name="Motif"),
        ),
        migrations.AlterField(
            model_name="leave",
            name="start_date",
            field=models.DateField(verbose_name="Date de début"),
        ),
        migrations.AlterField(
            model_name="leave",
            name="status",
            field=models.CharField(
                choices=[
                    ("demande", "Demandé"),
                    ("approuve", "Approuvé"),
                    ("rejete", "Rejeté"),
                ],
                default="demande",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
        ),
        migrations.AlterField(
            model_name="leavetype",
            name="days_per_year",
            field=models.IntegerField(default=20, verbose_name="Jours par an"),
        ),
        migrations.AlterField(
            model_name="leavetype",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="base_salary",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Salaire de base"
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="bonuses",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Primes"
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="deductions",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Retenues"
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payrolls",
                to="hr.employee",
                verbose_name="Employé",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="month",
            field=models.DateField(verbose_name="Mois"),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="net_salary",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Salaire net"
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, upload_to="payrolls/", verbose_name="Fichier PDF"
            ),
        ),
    ]
