# Generated by Django 4.2.11 on 2026-02-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0002_alter_attendance_check_in_alter_attendance_check_out_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="bio",
            field=models.TextField(blank=True, verbose_name="Biographie"),
        ),
        migrations.AddField(
            model_name="employee",
            name="is_key_staff",
            field=models.BooleanField(
                default=False, verbose_name="Personnel clé (afficher sur le site)"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True, verbose_name="LinkedIn"),
        ),
        migrations.AddField(
            model_name="employee",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="hr/employees/", verbose_name="Photo"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="photo_url",
            field=models.URLField(blank=True, null=True, verbose_name="URL photo"),
        ),
    ]
