# Generated by Django 4.2.11 on 2026-02-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0003_employee_bio_employee_is_key_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="position_custom",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Poste personnalisé"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="contract_type",
            field=models.CharField(
                choices=[
                    ("cdd", "CDD"),
                    ("cdi", "CDI"),
                    ("consultant", "Consultant"),
                    ("stage", "Stage"),
                ],
                max_length=20,
                verbose_name="Type de contrat",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.CharField(
                choices=[
                    ("direction", "Direction"),
                    ("rh", "Ressources Humaines"),
                    ("comptabilite", "Comptabilité & Finance"),
                    ("commercial", "Commercial"),
                    ("operations", "Opérations"),
                    ("support", "Support Client"),
                    ("it", "Informatique"),
                    ("logistique", "Logistique"),
                    ("autre", "Autre"),
                ],
                default="autre",
                max_length=50,
                verbose_name="Département",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(
                choices=[
                    ("directeur_general", "Directeur Général"),
                    ("directeur_adjoint", "Directeur Adjoint"),
                    ("directeur_agence", "Directeur d'Agence"),
                    ("manager", "Manager"),
                    ("chef_departement", "Chef de Département"),
                    ("superviseur", "Superviseur"),
                    ("responsable_rh", "Responsable RH"),
                    ("assistant_rh", "Assistant RH"),
                    ("responsable_comptable", "Responsable Comptable"),
                    ("comptable", "Comptable"),
                    ("caissier", "Caissier"),
                    ("responsable_commercial", "Responsable Commercial"),
                    ("agent_commercial", "Agent Commercial"),
                    ("conseiller_client", "Conseiller Client"),
                    ("responsable_operations", "Responsable Opérations"),
                    ("technicien", "Technicien"),
                    ("installateur", "Installateur"),
                    ("responsable_support", "Responsable Support"),
                    ("agent_guichet", "Agent de Guichet"),
                    ("agent_support", "Agent Support"),
                    ("responsable_it", "Responsable IT"),
                    ("developpeur", "Développeur"),
                    ("administrateur_systeme", "Administrateur Système"),
                    ("stagiaire", "Stagiaire"),
                    ("autre", "Autre"),
                ],
                default="autre",
                max_length=50,
                verbose_name="Poste",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="status",
            field=models.CharField(
                choices=[
                    ("actif", "Actif"),
                    ("suspendu", "Suspendu"),
                    ("sorti", "Sorti"),
                    ("conge", "En congé"),
                ],
                default="actif",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
