# Generated by Django 4.2.11 on 2026-02-02 09:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        (
            "agencies",
            "0003_agency_background_image_agency_background_image_url_and_more",
        ),
        ("hr", "0004_employee_position_custom_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeBadge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "badge_code",
                    models.CharField(
                        editable=False,
                        max_length=100,
                        unique=True,
                        verbose_name="Code badge",
                    ),
                ),
                (
                    "qr_secret",
                    models.CharField(
                        editable=False, max_length=64, verbose_name="Secret QR"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("suspendu", "Suspendu"),
                            ("perdu", "Perdu"),
                            ("annule", "Annulé"),
                        ],
                        default="actif",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "issued_date",
                    models.DateField(auto_now_add=True, verbose_name="Date d'émission"),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'expiration"
                    ),
                ),
                (
                    "can_access_all_agencies",
                    models.BooleanField(
                        default=False, verbose_name="Accès toutes agences"
                    ),
                ),
                (
                    "can_activate_monitor",
                    models.BooleanField(
                        default=True, verbose_name="Peut activer moniteur"
                    ),
                ),
                (
                    "can_use_kiosk",
                    models.BooleanField(
                        default=True, verbose_name="Peut utiliser borne"
                    ),
                ),
                (
                    "last_scan_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernier scan"
                    ),
                ),
                (
                    "scan_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de scans"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badge",
                        to="hr.employee",
                        verbose_name="Employé",
                    ),
                ),
                (
                    "last_scan_agency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="last_badge_scans",
                        to="agencies.agency",
                        verbose_name="Dernière agence scannée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Badge employé",
                "verbose_name_plural": "Badges employés",
            },
        ),
        migrations.CreateModel(
            name="BadgeScanLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scan_type",
                    models.CharField(
                        choices=[
                            ("presence", "Pointage présence"),
                            ("monitor", "Activation moniteur"),
                            ("kiosk", "Accès borne"),
                            ("dashboard", "Accès dashboard"),
                            ("door", "Accès porte"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type de scan",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("success", "Succès"),
                            ("denied", "Refusé"),
                            ("expired", "Expiré"),
                            ("invalid", "Invalide"),
                        ],
                        max_length=20,
                        verbose_name="Résultat",
                    ),
                ),
                (
                    "scanned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Scanné le"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "device_info",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Info appareil"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agencies.agency",
                        verbose_name="Agence",
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_logs",
                        to="hr.employeebadge",
                        verbose_name="Badge",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de scan badge",
                "verbose_name_plural": "Logs de scans badges",
                "ordering": ["-scanned_at"],
            },
        ),
    ]
