# Generated by Django 4.2.11 on 2026-02-01 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="post_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Post-nom"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Créer"),
                    ("update", "Modifier"),
                    ("delete", "Supprimer"),
                    ("approve", "Approuver"),
                    ("reject", "Rejeter"),
                    ("export", "Exporter"),
                ],
                max_length=20,
                verbose_name="Action",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="changes",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Changements"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="Adresse IP"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="module",
            field=models.CharField(max_length=50, verbose_name="Module"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="object_id",
            field=models.CharField(max_length=255, verbose_name="ID Objet"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="object_repr",
            field=models.CharField(max_length=255, verbose_name="Objet"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date/Heure"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Créer"),
                    ("read", "Lire"),
                    ("update", "Modifier"),
                    ("delete", "Supprimer"),
                    ("export", "Exporter"),
                    ("approve", "Approuver"),
                ],
                max_length=20,
                verbose_name="Action",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="module",
            field=models.CharField(
                choices=[
                    ("core", "Core"),
                    ("geo", "Géographie"),
                    ("accounts", "Comptes"),
                    ("hr", "RH"),
                    ("crm", "CRM"),
                    ("billing", "Facturation"),
                    ("operations", "Opérations"),
                    ("support", "Support"),
                    ("cms", "CMS"),
                    ("agencies", "Agences"),
                ],
                max_length=20,
                verbose_name="Module",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("admin", "Admin"),
                    ("rh", "RH"),
                    ("comptable", "Comptable"),
                    ("operations", "Opérations"),
                    ("agent_commercial", "Agent Commercial"),
                    ("employe", "Employé"),
                    ("client", "Client"),
                ],
                max_length=20,
                verbose_name="Rôle",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active_user",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Téléphone"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/photos/", verbose_name="Photo"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("admin", "Admin"),
                    ("rh", "RH"),
                    ("comptable", "Comptable"),
                    ("operations", "Opérations"),
                    ("agent_commercial", "Agent Commercial"),
                    ("employe", "Employé"),
                    ("client", "Client"),
                ],
                default="employe",
                max_length=20,
                verbose_name="Rôle",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
        ),
    ]
