# Generated by Django 4.2.11 on 2026-02-02 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("agencies", "0002_agency_province_alter_agency_address_and_more"),
        ("accounts", "0002_user_post_name_alter_auditlog_action_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="agency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="agencies.agency",
                verbose_name="Agence",
            ),
        ),
    ]
