# Generated by Django 4.2.11 on 2026-02-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_agency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Administrateur"),
                    ("employe", "Employé"),
                    ("client", "Client"),
                ],
                max_length=20,
                verbose_name="Rôle",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Administrateur"),
                    ("employe", "Employé"),
                    ("client", "Client"),
                ],
                default="client",
                max_length=20,
                verbose_name="Rôle",
            ),
        ),
    ]
