# Generated by Django 4.2.11 on 2026-02-01 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("geo", "0002_alter_commune_code_alter_commune_name_and_more"),
        ("agencies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="province",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agencies",
                to="geo.province",
                verbose_name="Province",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="agency",
            name="address",
            field=models.TextField(verbose_name="Adresse"),
        ),
        migrations.AlterField(
            model_name="agency",
            name="code",
            field=models.CharField(max_length=20, unique=True, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="agency",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="agency",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="agency",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AlterField(
            model_name="agency",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_agencies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsable",
            ),
        ),
        migrations.AlterField(
            model_name="agency",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="agency",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="Téléphone"),
        ),
        migrations.AlterField(
            model_name="agency",
            name="territory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agencies",
                to="geo.territory",
                verbose_name="Territoire",
            ),
        ),
        migrations.AlterField(
            model_name="agency",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
        ),
    ]
