# Generated by Django 4.2.11 on 2026-02-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agencies", "0002_agency_province_alter_agency_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="background_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="agencies/backgrounds/",
                verbose_name="Image de fond",
            ),
        ),
        migrations.AddField(
            model_name="agency",
            name="background_image_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="URL image de fond"
            ),
        ),
        migrations.AddField(
            model_name="agency",
            name="icon_svg",
            field=models.TextField(
                blank=True,
                help_text="Code SVG personnalisé pour l'agence",
                verbose_name="Icône SVG",
            ),
        ),
    ]
