# Generated by Django 4.2.11 on 2026-02-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "agencies",
            "0003_agency_background_image_agency_background_image_url_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Ex: -4.441931 pour Kinshasa",
                max_digits=9,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AddField(
            model_name="agency",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Ex: 15.266293 pour Kinshasa",
                max_digits=9,
                null=True,
                verbose_name="Longitude",
            ),
        ),
    ]
