# Generated by Django 4.2.11 on 2026-02-02 08:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "agencies",
            "0003_agency_background_image_agency_background_image_url_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Counter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(verbose_name="Numéro du guichet"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Nom personnalisé"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Disponible"),
                            ("busy", "Occupé"),
                            ("closed", "Fermé"),
                            ("break", "Pause"),
                        ],
                        default="closed",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counters",
                        to="agencies.agency",
                        verbose_name="Agence",
                    ),
                ),
                (
                    "current_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_counters",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Agent actuel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guichet",
                "verbose_name_plural": "Guichets",
                "ordering": ["agency", "number"],
            },
        ),
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom du service"),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Durée estimée (minutes)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Icône (classe)"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="blue", max_length=20, verbose_name="Couleur"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Type de service",
                "verbose_name_plural": "Types de services",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Lundi"),
                            (1, "Mardi"),
                            (2, "Mercredi"),
                            (3, "Jeudi"),
                            (4, "Vendredi"),
                            (5, "Samedi"),
                            (6, "Dimanche"),
                        ],
                        verbose_name="Jour de la semaine",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Heure de début")),
                ("end_time", models.TimeField(verbose_name="Heure de fin")),
                (
                    "max_appointments",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Nombre max de RDV"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slots",
                        to="agencies.agency",
                        verbose_name="Agence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Créneau horaire",
                "verbose_name_plural": "Créneaux horaires",
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="QueueTicket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ticket_number",
                    models.CharField(max_length=10, verbose_name="Numéro de ticket"),
                ),
                (
                    "client_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nom du client"
                    ),
                ),
                (
                    "client_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "En attente"),
                            ("called", "Appelé"),
                            ("serving", "En service"),
                            ("completed", "Terminé"),
                            ("cancelled", "Annulé"),
                            ("no_show", "Absent"),
                        ],
                        default="waiting",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("priority", "Prioritaire"),
                            ("vip", "VIP"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "date",
                    models.DateField(default=datetime.date.today, verbose_name="Date"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "called_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Appelé le"
                    ),
                ),
                (
                    "served_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Pris en charge le"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Terminé le"
                    ),
                ),
                (
                    "estimated_wait_time",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Temps d'attente estimé"
                    ),
                ),
                (
                    "queue_position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Position dans la file"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_tickets",
                        to="agencies.agency",
                        verbose_name="Agence",
                    ),
                ),
                (
                    "counter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="appointments.counter",
                        verbose_name="Guichet",
                    ),
                ),
                (
                    "served_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="served_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Servi par",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="queue_tickets",
                        to="appointments.servicetype",
                        verbose_name="Service",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="queue_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket de file",
                "verbose_name_plural": "Tickets de file",
                "ordering": ["date", "priority", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="counter",
            name="current_ticket",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="serving_counter",
                to="appointments.queueticket",
                verbose_name="Ticket en cours",
            ),
        ),
        migrations.AddField(
            model_name="counter",
            name="services",
            field=models.ManyToManyField(
                related_name="counters",
                to="appointments.servicetype",
                verbose_name="Services traités",
            ),
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=200, verbose_name="Nom du client"),
                ),
                (
                    "client_phone",
                    models.CharField(max_length=20, verbose_name="Téléphone"),
                ),
                (
                    "client_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("time", models.TimeField(verbose_name="Heure")),
                (
                    "confirmation_code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Code de confirmation"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("confirmed", "Confirmé"),
                            ("in_progress", "En cours"),
                            ("completed", "Terminé"),
                            ("cancelled", "Annulé"),
                            ("no_show", "Absent"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Confirmé le"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Terminé le"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Annulé le"
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="Raison d'annulation"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="agencies.agency",
                        verbose_name="Agence",
                    ),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Traité par",
                    ),
                ),
                (
                    "queue_ticket",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointment",
                        to="appointments.queueticket",
                        verbose_name="Ticket de file",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="appointments.servicetype",
                        verbose_name="Service",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rendez-vous",
                "verbose_name_plural": "Rendez-vous",
                "ordering": ["date", "time"],
            },
        ),
        migrations.CreateModel(
            name="DailyQueueStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "total_tickets",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total tickets"
                    ),
                ),
                (
                    "completed_tickets",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tickets traités"
                    ),
                ),
                (
                    "cancelled_tickets",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tickets annulés"
                    ),
                ),
                (
                    "no_show_tickets",
                    models.PositiveIntegerField(default=0, verbose_name="Absents"),
                ),
                (
                    "avg_wait_time",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Temps d'attente moyen (min)",
                    ),
                ),
                (
                    "avg_service_time",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Temps de service moyen (min)",
                    ),
                ),
                (
                    "peak_hour",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure de pointe"
                    ),
                ),
                (
                    "peak_wait_time",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Temps d'attente en pointe (min)",
                    ),
                ),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_stats",
                        to="agencies.agency",
                        verbose_name="Agence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statistiques file d'attente",
                "verbose_name_plural": "Statistiques files d'attente",
                "ordering": ["-date"],
                "unique_together": {("agency", "date")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="counter",
            unique_together={("agency", "number")},
        ),
    ]
