# Generated by Django 4.2.11 on 2026-02-01 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("agencies", "0002_agency_province_alter_agency_address_and_more"),
        ("geo", "0002_alter_commune_code_alter_commune_name_and_more"),
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="address",
            field=models.TextField(verbose_name="Adresse"),
        ),
        migrations.AlterField(
            model_name="client",
            name="agency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients",
                to="agencies.agency",
                verbose_name="Agence",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="commune",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="geo.commune",
                verbose_name="Commune",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="geo.country",
                verbose_name="Pays",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="client",
            name="date_of_birth",
            field=models.DateField(verbose_name="Date de naissance"),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="client",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="Prénom"),
        ),
        migrations.AlterField(
            model_name="client",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="client",
            name="nationality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="geo.nationality",
                verbose_name="Nationalité",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="nif",
            field=models.CharField(max_length=50, unique=True, verbose_name="NIF"),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="Téléphone"),
        ),
        migrations.AlterField(
            model_name="client",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="clients/photos/", verbose_name="Photo"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="place_of_birth",
            field=models.CharField(max_length=200, verbose_name="Lieu de naissance"),
        ),
        migrations.AlterField(
            model_name="client",
            name="post_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Post-nom"),
        ),
        migrations.AlterField(
            model_name="client",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="geo.province",
                verbose_name="Province",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="status",
            field=models.CharField(
                choices=[
                    ("prospect", "Prospect"),
                    ("actif", "Actif"),
                    ("suspendu", "Suspendu"),
                ],
                default="prospect",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="Séparés par des virgules",
                max_length=500,
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="territory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="geo.territory",
                verbose_name="Territoire",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="crm.client",
                verbose_name="Client",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="contract_type",
            field=models.CharField(
                choices=[
                    ("mensuel", "Mensuel"),
                    ("consommation", "Consommation"),
                    ("forfait", "Forfait"),
                ],
                max_length=20,
                verbose_name="Type de contrat",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="currency",
            field=models.CharField(default="USD", max_length=3, verbose_name="Devise"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date de fin"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="rate",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Tarif"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="crm.site",
                verbose_name="Site",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="start_date",
            field=models.DateField(verbose_name="Date de début"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[
                    ("actif", "Actif"),
                    ("inactif", "Inactif"),
                    ("suspendu", "Suspendu"),
                ],
                default="actif",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
        ),
        migrations.AlterField(
            model_name="site",
            name="address",
            field=models.TextField(verbose_name="Adresse"),
        ),
        migrations.AlterField(
            model_name="site",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sites",
                to="crm.client",
                verbose_name="Client",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="commune",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="geo.commune",
                verbose_name="Commune",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="contact_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Nom du contact"
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="contact_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Téléphone du contact"
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="geo.country",
                verbose_name="Pays",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="site",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AlterField(
            model_name="site",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="site",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="geo.province",
                verbose_name="Province",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="reference",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Référence"
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="territory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="geo.territory",
                verbose_name="Territoire",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
        ),
    ]
