# Generated by Django 4.2.11 on 2026-02-02 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "agencies",
            "0003_agency_background_image_agency_background_image_url_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("geo", "0002_alter_commune_code_alter_commune_name_and_more"),
        ("crm", "0002_alter_client_address_alter_client_agency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur associé",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="address",
            field=models.TextField(blank=True, verbose_name="Adresse"),
        ),
        migrations.AlterField(
            model_name="client",
            name="agency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients",
                to="agencies.agency",
                verbose_name="Agence",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="commune",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="geo.commune",
                verbose_name="Commune",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="geo.country",
                verbose_name="Pays",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="date_of_birth",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de naissance"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="nationality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="geo.nationality",
                verbose_name="Nationalité",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="nif",
            field=models.CharField(blank=True, max_length=50, verbose_name="NIF"),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Téléphone"),
        ),
        migrations.AlterField(
            model_name="client",
            name="place_of_birth",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Lieu de naissance"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="geo.province",
                verbose_name="Province",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="territory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="geo.territory",
                verbose_name="Territoire",
            ),
        ),
    ]
