# Generated by Django 4.2.11 on 2026-02-01 01:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commune",
            name="code",
            field=models.CharField(max_length=10, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="commune",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Commune"),
        ),
        migrations.AlterField(
            model_name="commune",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="communes",
                to="geo.province",
                verbose_name="Province",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="code",
            field=models.CharField(max_length=3, unique=True, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Pays"),
        ),
        migrations.AlterField(
            model_name="province",
            name="code",
            field=models.CharField(max_length=10, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="province",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provinces",
                to="geo.country",
                verbose_name="Pays",
            ),
        ),
        migrations.AlterField(
            model_name="province",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Province"),
        ),
        migrations.AlterField(
            model_name="territory",
            name="code",
            field=models.CharField(max_length=10, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="territory",
            name="commune",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="territories",
                to="geo.commune",
                verbose_name="Commune",
            ),
        ),
        migrations.AlterField(
            model_name="territory",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Territoire"),
        ),
        migrations.CreateModel(
            name="Nationality",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nationalité")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nationalities",
                        to="geo.country",
                        verbose_name="Pays",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nationalité",
                "verbose_name_plural": "Nationalités",
                "ordering": ["name"],
                "unique_together": {("country", "name")},
            },
        ),
    ]
