# Generated by Django 4.2.11 on 2026-02-01 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("compteur", "Compteur"),
                            ("transformateur", "Transformateur"),
                            ("disjoncteur", "Disjoncteur"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                ("reference", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("inactif", "Inactif"),
                            ("maintenance", "Maintenance"),
                            ("defaillant", "Défaillant"),
                        ],
                        default="actif",
                        max_length=20,
                    ),
                ),
                ("installation_date", models.DateField()),
                ("last_maintenance", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipments",
                        to="crm.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Équipement",
                "verbose_name_plural": "Équipements",
                "ordering": ["site", "equipment_type"],
            },
        ),
        migrations.CreateModel(
            name="Meter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("meter_number", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("inactif", "Inactif"),
                            ("defaillant", "Défaillant"),
                        ],
                        default="actif",
                        max_length=20,
                    ),
                ),
                ("service_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "equipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meter",
                        to="operations.equipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compteur",
                "verbose_name_plural": "Compteurs",
            },
        ),
        migrations.CreateModel(
            name="Intervention",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "intervention_type",
                    models.CharField(
                        choices=[
                            ("maintenance", "Maintenance"),
                            ("reparation", "Réparation"),
                            ("installation", "Installation"),
                            ("inspection", "Inspection"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planifiee", "Planifiée"),
                            ("en_cours", "En cours"),
                            ("completee", "Complétée"),
                            ("annulee", "Annulée"),
                        ],
                        default="planifiee",
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interventions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interventions",
                        to="crm.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intervention",
                "verbose_name_plural": "Interventions",
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="MeterReading",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reading_date", models.DateField()),
                ("reading_value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="operations.meter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relevé de compteur",
                "verbose_name_plural": "Relevés de compteur",
                "ordering": ["-reading_date"],
                "unique_together": {("meter", "reading_date")},
            },
        ),
    ]
